### ISSUE TITLE
Document the order of a facade plugin

### ISSUE THREAD

**Issue by mmalvik** [FirelyTeam/firely-docs-firely-server#35]
Hi!

I think the documentation needs to specify which order (`[VonkConfiguration(order: X]`) is valid for a facade plugin.

It is my understanding that this needs to be lower than 241.
Otherwise you run into some issue where something else resolves the `ISearchRepository` and `IResourceChangeRepository`.

**Comment by cknaap** [comment]
Hi @mmalvik ,

Thanks for your comment. You are right, we fixed it in #58 .
